// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtMYeeU9CSGXvd9HyV2vk2qttf-sdc66c',
    appId: '1:274884115180:android:44e01dd364326f6d6103c9',
    messagingSenderId: '274884115180',
    projectId: 'gixat-4wk',
    storageBucket: 'gixat-4wk.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRwvbM1EWCyFQjyPAIKnAqHTqf4P8wTAQ',
    appId: '1:274884115180:ios:2a62865086d19ff36103c9',
    messagingSenderId: '274884115180',
    projectId: 'gixat-4wk',
    storageBucket: 'gixat-4wk.firebasestorage.app',
    iosBundleId: 'ae.4wk.gixat4wk',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDD9SzmI7jxnHDRn6ntQnb6AtNDtH35O3Y',
    appId: '1:274884115180:web:5856d0d60de731cc6103c9',
    messagingSenderId: '274884115180',
    projectId: 'gixat-4wk',
    authDomain: 'gixat-4wk.firebaseapp.com',
    storageBucket: 'gixat-4wk.firebasestorage.app',
    measurementId: 'G-MH66J6N42E',
  );

}