// Middle East countries and their phone codes
const List<Map<String, String>> meCountries = [
  {'name': 'Saudi Arabia', 'code': '+966'},
  {'name': 'United Arab Emirates', 'code': '+971'},
  {'name': 'Kuwait', 'code': '+965'},
  {'name': 'Qatar', 'code': '+974'},
  {'name': 'Bahrain', 'code': '+973'},
  {'name': 'Oman', 'code': '+968'},
  {'name': 'Jordan', 'code': '+962'},
  {'name': 'Lebanon', 'code': '+961'},
  {'name': 'Egypt', 'code': '+20'},
  {'name': 'Iraq', 'code': '+964'},
  {'name': 'Palestine', 'code': '+970'},
  {'name': 'Syria', 'code': '+963'},
  {'name': 'Yemen', 'code': '+967'},
  {'name': 'Other', 'code': ''},
];

// Cities for each country (add more as needed)
const Map<String, List<String>> meCountryCities = {
  'United Arab Emirates': [
    'Abu Dhabi',
    'Dubai',
    'Sharjah',
    'Ajman',
    'Fujairah',
    'Ras Al Khaimah',
    'Umm Al Quwain',
    'Al Ain',
    'Khor Fakkan',
    'Dibba Al-Fujairah',
    'Kalba',
    'Madinat Zayed',
    'Liwa Oasis',
    'Ghayathi',
    'Ruwais',
    'Hatta',
  ],
  'Saudi Arabia': [
    'Riyadh',
    'Jeddah',
    'Mecca',
    'Medina',
    'Dammam',
    'Khobar',
    'Dhahran',
    'Tabuk',
    'Buraidah',
    'Hail',
    'Abha',
    'Khamis Mushait',
    'Najran',
    'Jazan',
    'Al Qassim',
    'Al Hofuf',
    'Al Mubarraz',
    'Yanbu',
    'Al Jubail',
    'Sakaka',
    'Arar',
    'Al Bahah',
    'Al Khafji',
  ],
  'Kuwait': [
    'Kuwait City',
    'Hawalli',
    'Salmiya',
    'Farwaniya',
    'Ahmadi',
    'Jahra',
    'Fahaheel',
    'Mubarak Al-Kabeer',
  ],
  'Qatar': [
    'Doha',
    'Al Rayyan',
    'Umm Salal',
    'Al Wakrah',
    'Al Khor',
    'Al Daayen',
    'Al Shamal',
    'Mesaieed',
    'Dukhan',
  ],
  'Bahrain': [
    'Manama',
    'Muharraq',
    'Riffa',
    'Isa Town',
    'Sitra',
    'Budaiya',
    'Jidhafs',
    'Hamad Town',
    'Aali',
  ],
  'Oman': [
    'Muscat',
    'Salalah',
    'Sohar',
    'Nizwa',
    'Sur',
    'Ibri',
    'Barka',
    'Rustaq',
    'Buraimi',
    'Khasab',
    'Ibra',
  ],
  'Jordan': [
    'Amman',
    'Zarqa',
    'Irbid',
    'Russeifa',
    'Aqaba',
    'Mafraq',
    'Madaba',
    'Salt',
    'Jerash',
    'Tafila',
    'Ma’an',
  ],
  'Lebanon': [
    'Beirut',
    'Tripoli',
    'Sidon',
    'Tyre',
    'Zahle',
    'Jounieh',
    'Baabda',
    'Aley',
    'Baalbek',
    'Nabatieh',
  ],
  'Egypt': [
    'Cairo',
    'Alexandria',
    'Giza',
    'Shubra El Kheima',
    'Port Said',
    'Suez',
    'Luxor',
    'Asyut',
    'Ismailia',
    'Faiyum',
    'Zagazig',
    'Aswan',
    'Damietta',
    'Damanhur',
    'Beni Suef',
    'Qena',
    'Sohag',
    'Hurghada',
    '6th of October City',
  ],
  'Iraq': [
    'Baghdad',
    'Basra',
    'Mosul',
    'Erbil',
    'Kirkuk',
    'Sulaymaniyah',
    'Najaf',
    'Karbala',
    'Diwaniyah',
    'Nasiriyah',
    'Amarah',
    'Hillah',
    'Dohuk',
    'Ramadi',
    'Kut',
    'Tikrit',
  ],
  'Palestine': [
    'Ramallah',
    'Gaza',
    'Hebron',
    'Nablus',
    'Jenin',
    'Tulkarm',
    'Qalqilya',
    'Bethlehem',
    'Jericho',
    'Rafah',
    'Khan Yunis',
    'Deir al-Balah',
  ],
  'Syria': [
    'Damascus',
    'Aleppo',
    'Homs',
    'Latakia',
    'Hama',
    'Deir ez-Zor',
    'Raqqa',
    'Idlib',
    'Daraa',
    'Tartus',
    'Al-Hasakah',
    'As-Suwayda',
  ],
  'Yemen': [
    "Sana'a",
    'Aden',
    'Taiz',
    'Al Hudaydah',
    'Ibb',
    'Mukalla',
    'Zinjibar',
    'Sayun',
    'Dhamar',
    'Amran',
    'Al-Mukalla',
  ],
  'Other': [],
};
